/** 比奇堡贴贴盲袋（id9）评价种子：昵称为常见网名/称呼，评论以中文为主；英文仅供切语言时简短对照 */
export type Bb9ReviewSeedRow = {
  id: string;
  name: string;
  date: string;
  rating: number;
  boxed: boolean;
  textCn: string;
  textEn: string;
};

export const BB9_REVIEW_SEED: Bb9ReviewSeedRow[] = [
  {
    id: 'bb9-r-01',
    name: '阿雯',
    date: '5/4/2026',
    rating: 5,
    boxed: false,
    textCn: '迫不及待的拆开我心心念念的宝宝，看着是预售的，还是发了，客服态度超好，物流特快，打包的也很细心 谢谢宝',
    textEn: 'Preorder still shipped fast; kind service, quick delivery, careful packing. Thank you!',
  },
  {
    id: 'bb9-r-02',
    name: '林momo',
    date: '5/4/2026',
    rating: 5,
    boxed: true,
    textCn: '端盒十袋一口气拆完，每只都想摸一遍。海绵宝宝和派大星那袋跟闺蜜换到了想要的款，贴贴毛绒软乎乎的，解压又治愈。',
    textEn: 'Full case of ten bags—traded pulls with a friend; soft plush stickers feel very soothing.',
  },
  {
    id: 'bb9-r-03',
    name: 'Kevin_633',
    date: '5/3/2026',
    rating: 5,
    boxed: false,
    textCn: '单袋两只没重复，绒毛比想象里厚实，挂在装饰包上被问好几次哪里买，比奇堡这波真的蛮可爱。',
    textEn: 'One bag, two unique pieces; thicker fluff than expected. People asked where I bought them.',
  },
  {
    id: 'bb9-r-04',
    name: '陈小姐',
    date: '5/3/2026',
    rating: 4,
    boxed: false,
    textCn: '冲着「比奇堡里有什么」来的，外箱角保护得很好，泡沫塞得满，两只脸都很正，会再回购送人。',
    textEn: 'Corners protected, plenty of padding; faces look good. Will buy again as gifts.',
  },
  {
    id: 'bb9-r-05',
    name: '小王',
    date: '5/2/2026',
    rating: 5,
    boxed: false,
    textCn: '本来怕预售要等很久，结果提前发了，客服回得也快。两只贴贴摆桌上，同事经过都要捏一下哈哈。',
    textEn: 'Arrived earlier than expected; support replied quickly. Coworkers keep squeezing the two patches.',
  },
  {
    id: 'bb9-r-06',
    name: '豆豆妈',
    date: '5/2/2026',
    rating: 5,
    boxed: true,
    textCn: '端盒摆起来像小型水族墙，磁吸一贴冰箱整个很有梗，我妈还问是不是会变多的那种可爱。',
    textEn: 'Full case looks like a mini wall display; magnets on the fridge look very fun.',
  },
  {
    id: 'bb9-r-07',
    name: '没睡醒',
    date: '5/1/2026',
    rating: 5,
    boxed: false,
    textCn: '拆袋像在拆迷你表情包，章鱼哥那眼神太欠揍，贴在屏幕边边每天跟它对线（精神上）。',
    textEn: 'Unboxing feels like meme drops; Squidward’s eyes are perfect for desk-side jokes.',
  },
  {
    id: 'bb9-r-08',
    name: 'Amy',
    date: '5/1/2026',
    rating: 4,
    boxed: true,
    textCn: '十袋里有一袋外盒小压到，里面贴贴没事。端盒价钱肉疼但拆完满足感很够，跟朋友分袋刚刚好。',
    textEn: 'One shipper corner dinged; plushies fine. Pricey full case but very satisfying to split with friends.',
  },
  {
    id: 'bb9-r-09',
    name: '张先生',
    date: '4/30/2026',
    rating: 5,
    boxed: false,
    textCn: '磁吸比想象中牢，洞洞板上甩几下也没掉；路障派大星那个配色看了会饿，像草莓牛奶。',
    textEn: 'Magnets hold well on a pegboard; Patrick’s colors look sweet like strawberry milk.',
  },
  {
    id: 'bb9-r-10',
    name: '肥羊',
    date: '4/30/2026',
    rating: 5,
    boxed: false,
    textCn: '单抽没踩雷，两只表情像在演连续剧，已经变成我办公桌番外篇固定班底。',
    textEn: 'Single pull felt safe; two expressions look like a little office side story.',
  },
  {
    id: 'bb9-r-11',
    name: '阿豪888',
    date: '4/29/2026',
    rating: 5,
    boxed: true,
    textCn: '端盒就是为了名场面，墓碑章鱼哥摆书架像在演黑色幽默短剧，朋友来家里都先拍照。',
    textEn: 'Bought the full case for iconic scenes; Squidward display looks hilariously photogenic.',
  },
  {
    id: 'bb9-r-12',
    name: '路人用户',
    date: '4/29/2026',
    rating: 5,
    boxed: false,
    textCn: '背面磁吸还能夹便签，开会无聊就盘它们，主管以为我在盘核桃其实是比奇堡（不要学坏）。',
    textEn: 'Magnetic backs hold notes; good desk fidget during meetings.',
  },
  {
    id: 'bb9-r-13',
    name: '林小姐',
    date: '4/28/2026',
    rating: 4,
    boxed: false,
    textCn: '有一只绒毛稍微不对称，但整体瑕不掩瑜，客服说可以登记处理，我先留着当限定款心态。',
    textEn: 'One piece slightly asymmetric; still cute. Support offered help if I want a swap.',
  },
  {
    id: 'bb9-r-14',
    name: '匿名777',
    date: '4/28/2026',
    rating: 5,
    boxed: true,
    textCn: '跟室友拼端盒，拆到超有梗的那几袋当场尖叫，邻居以为在看恐怖片其实是章鱼哥。',
    textEn: 'Split a case with roommates—very loud unboxing, very funny pulls.',
  },
  {
    id: 'bb9-r-15',
    name: '阿杰',
    date: '4/27/2026',
    rating: 5,
    boxed: false,
    textCn: '贴贴比想象轻，旅行塞侧袋刚好，安检人员还问是不是儿童玩具，我说这是大人的情绪稳定器。',
    textEn: 'Light for travel; fits in a side pocket. Told security it’s adult emotional support plush.',
  },
  {
    id: 'bb9-r-16',
    name: '小红薯用户',
    date: '4/27/2026',
    rating: 5,
    boxed: false,
    textCn: '两只凑成上班厌世二人组，挂在工牌绳上，开会低头看一眼就没那么想翻桌（一点点啦）。',
    textEn: 'Two pieces became my “work mood” duo on a lanyard; oddly calming.',
  },
  {
    id: 'bb9-r-17',
    name: 'Lisa',
    date: '4/26/2026',
    rating: 4,
    boxed: true,
    textCn: '端盒抱上楼像健身，但每袋拆开都像小烟花，整体还是很爽很值得。',
    textEn: 'Heavy to carry upstairs; each bag still felt exciting to open.',
  },
  {
    id: 'bb9-r-18',
    name: '吴先生',
    date: '4/26/2026',
    rating: 5,
    boxed: false,
    textCn: '贴在教室黑板边当比奇堡新闻联播，学生下课围着看，我说是教具其实是私货啦。',
    textEn: 'Stuck on a classroom board edge; students love gathering to look.',
  },
  {
    id: 'bb9-r-19',
    name: '婷婷',
    date: '4/25/2026',
    rating: 5,
    boxed: false,
    textCn: '单袋两只颜色很搭，像配好对的耳环，已经安利给整个社团。',
    textEn: 'One bag, two colors that match nicely; told the whole club to try.',
  },
  {
    id: 'bb9-r-20',
    name: '大卫L',
    date: '4/25/2026',
    rating: 5,
    boxed: true,
    textCn: '端盒每袋都像番外篇，摆成弧形像在海底隧道走路，中二但开心。',
    textEn: 'Full case feels like bonus episodes; curved display looks fun on a shelf.',
  },
  {
    id: 'bb9-r-21',
    name: '用户883291',
    date: '4/24/2026',
    rating: 5,
    boxed: false,
    textCn: '预售说明写得很清楚，到货跟描述一致，没有照骗那种焦虑，这点很加分。',
    textEn: 'Preorder info was clear; item matched photos. That matters a lot.',
  },
  {
    id: 'bb9-r-22',
    name: '阿珍',
    date: '4/24/2026',
    rating: 4,
    boxed: false,
    textCn: '有一只磁吸稍弱，换到更铁的板面就牢了，算小功课，整体还是喜欢。',
    textEn: 'One magnet weaker; works better on a steel surface. Still like the set.',
  },
  {
    id: 'bb9-r-23',
    name: '小陈',
    date: '4/23/2026',
    rating: 5,
    boxed: true,
    textCn: '端盒送朋友当团建礼物，十袋一起拆很吵但很快乐，像集体回忆现场。',
    textEn: 'Gave a full case as a group gift; loud but happy unboxing together.',
  },
  {
    id: 'bb9-r-24',
    name: '幸福就好',
    date: '4/23/2026',
    rating: 5,
    boxed: false,
    textCn: '两只叠在一起像叠叠乐，手感像在捏小吐司，停不下来。',
    textEn: 'Stacking two feels like plush stacking toys; very squishable.',
  },
  {
    id: 'bb9-r-25',
    name: '阿May',
    date: '4/22/2026',
    rating: 5,
    boxed: false,
    textCn: '物流更新很勤，泡沫像云朵，贴贴拿出来像在云里捞星星。',
    textEn: 'Tracking updated often; lots of padding; opening felt special.',
  },
  {
    id: 'bb9-r-26',
    name: 'Jason',
    date: '4/22/2026',
    rating: 5,
    boxed: true,
    textCn: '端盒当生日礼物，对方拆到喜欢的角色直接尖叫，场面一度很失控。',
    textEn: 'Full case as a birthday gift—they screamed when they pulled a favorite.',
  },
  {
    id: 'bb9-r-27',
    name: '不买睡不着',
    date: '4/21/2026',
    rating: 4,
    boxed: false,
    textCn: '最想抽的梗款没抽到，但两只常规款也很好笑，下次再战。',
    textEn: 'Missed my dream meme pull; regulars still funny. Will try again.',
  },
  {
    id: 'bb9-r-28',
    name: '小林',
    date: '4/21/2026',
    rating: 5,
    boxed: false,
    textCn: '贴在游戏机旁边，输一局就摸一下海绵宝宝，心理安慰用，有效。',
    textEn: 'Beside my console—rub SpongeBob after a loss for moral support. It helps.',
  },
];
